//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class billeterasMonedas
    {
        public long id { get; set; }
        public long fk_usuario { get; set; }
        public long fk_moneda { get; set; }
        public decimal cantidad { get; set; }
    }
}
