//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptoBackend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cryptomarcaEntities : DbContext
    {
        public cryptomarcaEntities()
            : base("name=cryptomarcaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<billeterasMonedas> billeterasMonedas { get; set; }
        public virtual DbSet<monedas> monedas { get; set; }
        public virtual DbSet<movimientos> movimientos { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<tipoMovimientos> tipoMovimientos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
