//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class monedas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monedas()
        {
            this.billeterasMonedas = new HashSet<billeterasMonedas>();
            this.movimientos = new HashSet<movimientos>();
            this.movimientos1 = new HashSet<movimientos>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public decimal cotizacion { get; set; }
        public System.DateTime fecha_cotizacion { get; set; }
        public string direccion_contrato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billeterasMonedas> billeterasMonedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientos> movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientos> movimientos1 { get; set; }
    }
}
