//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class monedas
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public decimal cotizacion { get; set; }
        public System.DateTime fecha_cotizacion { get; set; }
        public string direccion_contrato { get; set; }
    }
}
