//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptoBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.billeterasMonedas = new HashSet<billeterasMonedas>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string dni { get; set; }
        public long fk_provincia { get; set; }
        public long fk_banco { get; set; }
        public string cbu { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public bool activo { get; set; }
    
        public virtual bancos bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billeterasMonedas> billeterasMonedas { get; set; }
        public virtual provincias provincias { get; set; }
    }
}
